words = [
    # --- 1. الشحن والنقل الدولي ---
    {"en": "Shipment", "ar": "الشحنة", "pronunciation": "شِيبْمِينْت", "ex_en": "The shipment will arrive tomorrow morning.", "ex_ar": "ستصل الشحنة صباح الغد.", "category": "🚚 الشحن والنقل الدولي"},
    {"en": "Cargo", "ar": "البضائع / الحمولة", "pronunciation": "كَارْجُو", "ex_en": "The ship is carrying heavy cargo.", "ex_ar": "السفينة تحمل بضائع ثقيلة.", "category": "🚚 الشحن والنقل الدولي"},
    {"en": "Freight Forwarder", "ar": "وكيل الشحن", "pronunciation": "فْرِيت فَوْرْوَرْدَر", "ex_en": "Our freight forwarder handled the sea freight smoothly.", "ex_ar": "تولى وكيل الشحن الخاص بنا عملية الشحن البحري بسلاسة.", "category": "🚚 الشحن والنقل الدولي"},
    {"en": "Bill of Lading", "ar": "بوليصة الشحن", "pronunciation": "بِلْ أُوف لَيْدِينْج", "ex_en": "The Bill of Lading is a mandatory document for export.", "ex_ar": "بوليصة الشحن هي وثيقة إلزامية للتصدير.", "category": "🚚 الشحن والنقل الدولي"},
    {"en": "Waybill", "ar": "بوليصة نقل", "pronunciation": "وَيْبِل", "ex_en": "Make sure the air waybill is attached to the package.", "ex_ar": "تأكد من إرفاق بوليصة النقل الجوي بالطرد.", "category": "🚚 الشحن والنقل الدولي"},
    {"en": "Fleet Management", "ar": "إدارة الأسطول", "pronunciation": "فْلِيت مَانِيجْمِينْت", "ex_en": "Effective fleet management reduces fuel costs.", "ex_ar": "إدارة الأسطول الفعّالة تقلل تكاليف الوقود.", "category": "🚚 الشحن والنقل الدولي"},
    {"en": "Intermodal Transportation", "ar": "النقل متعدد الوسائط", "pronunciation": "إِنْتَرْمُودَال تْرَانْسْبُورْتَيْشَن", "ex_en": "Intermodal transportation combines rail and truck freight.", "ex_ar": "يجمع النقل متعدد الوسائط بين الشحن عبر السكك الحديدية والشاحنات.", "category": "🚚 الشحن والنقل الدولي"},
    {"en": "Demurrage", "ar": "غرامة تأخير الأرضية", "pronunciation": "دِيمِيرِيج", "ex_en": "We paid demurrage fees because the container was delayed at the port.", "ex_ar": "دفعنا رسوم غرامة تأخير لأن الحاوية تأخرت في الميناء.", "category": "🚚 الشحن والنقل الدولي"},

    # --- 2. إدارة المستودعات والتخزين ---
    {"en": "Warehouse", "ar": "المستودع / المخزن", "pronunciation": "وِيرْ هَاوْس", "ex_en": "We store all spare parts in the main warehouse.", "ex_ar": "نحن نخزن جميع قطع الغيار في المستودع الرئيسي.", "category": "🏢 إدارة المستودعات والتخزين"},
    {"en": "Inventory", "ar": "المخزون", "pronunciation": "إِنْفِنْتُورِي", "ex_en": "We need to do a full inventory count this weekend.", "ex_ar": "نحتاج إلى إجراء جرد كامل للمخزون نهاية هذا الأسبوع.", "category": "🏢 إدارة المستودعات والتخزين"},
    {"en": "Pallet", "ar": "طبلية / منصة نقالة", "pronunciation": "بَالِيت", "ex_en": "Please load these boxes onto the wooden pallet.", "ex_ar": "الرجاء تحميل هذه الصناديق على الطبلية الخشبية.", "category": "🏢 إدارة المستودعات والتخزين"},
    {"en": "Forklift", "ar": "رافعة شوكية", "pronunciation": "فُورْك لِفْت", "ex_en": "The worker is driving the forklift in the warehouse.", "ex_ar": "العامل يقود الرافعة الشوكية في المستودع.", "category": "🏢 إدارة المستودعات والتخزين"},
    {"en": "Cross-docking", "ar": "العبور المباشر لرصيف الشحن", "pronunciation": "كْرُوس دُوكِينْج", "ex_en": "Cross-docking eliminates the need for long-term storage.", "ex_ar": "العبور المباشر يلغي الحاجة للتخزين طويل الأمد.", "category": "🏢 إدارة المستودعات والتخزين"},
    {"en": "SKU (Stock Keeping Unit)", "ar": "وحدة حفظ المخزون", "pronunciation": "إس كَيْ يُو", "ex_en": "Each product has a unique SKU code.", "ex_ar": "كل منتج يمتلك رمز وحدة حفظ مخزون فريد.", "category": "🏢 إدارة المستودعات والتخزين"},
    {"en": "Put-away", "ar": "عملية التخزين في المكان المحدد", "pronunciation": "بُوت أُوَيْ", "ex_en": "The put-away process must be accurate to avoid losing items.", "ex_ar": "يجب أن تكون عملية التخزين في مكانها دقيقة لتفادي فقدان العناصر.", "category": "🏢 إدارة المستودعات والتخزين"},
    {"en": "Safety Stock", "ar": "مخزون الأمان", "pronunciation": "سَيْفْتِي سْتُوك", "ex_en": "We maintain safety stock to avoid shortages.", "ex_ar": "نحتفظ بمخزون أمان لتفادي أي نقص في الإمدادات.", "category": "🏢 إدارة المستودعات والتخزين"},

    # --- 3. إدارة سلاسل الإمداد والتخطيط ---
    {"en": "Supply Chain", "ar": "سلسلة الإمداد", "pronunciation": "سَبْلَايْ تَشِين", "ex_en": "A strong supply chain is key to business success.", "ex_ar": "سلسلة الإمداد القوية هي مفتاح نجاح الأعمال.", "category": "⚙️ سلاسل الإمداد والتخطيط"},
    {"en": "Lead Time", "ar": "فترة التوريد / وقت التنفيذ", "pronunciation": "لِيدْ تَايْم", "ex_en": "The lead time for this product is three weeks.", "ex_ar": "فترة التوريد لهذا المنتج هي 3 أسابيع.", "category": "⚙️ سلاسل الإمداد والتخطيط"},
    {"en": "Procurement", "ar": "المشتريات الاستراتيجية", "pronunciation": "بْرُوكْيُورْمِينْت", "ex_en": "The procurement team is looking for new international suppliers.", "ex_ar": "فريق المشتريات يبحث عن موردين دوليين جدد.", "category": "⚙️ سلاسل الإمداد والتخطيط"},
    {"en": "Just-In-Time (JIT)", "ar": "الإنتاج في الوقت المحدد تماماً", "pronunciation": "جَاسْت إِن تَايْم", "ex_en": "JIT strategy helps reduce inventory holding costs.", "ex_ar": "تساعد استراتيجية JIT في تقليل تكاليف الاحتفاظ بالمخزون.", "category": "⚙️ سلاسل الإمداد والتخطيط"},
    {"en": "Demand Forecasting", "ar": "التنبؤ بالطلب", "pronunciation": "دِيمَانْد فُورْكَاسْتِينْج", "ex_en": "Accurate demand forecasting helps optimize stock levels.", "ex_ar": "التنبؤ الدقيق بالطلب يساعد في تحسين مستويات المخزون.", "category": "⚙️ سلاسل الإمداد والتخطيط"},
    {"en": "Bullwhip Effect", "ar": "أثر سوط الحصان / تذبذب الطلب", "pronunciation": "بُولْ وِيب إِيفِكْت", "ex_en": "Poor communication causes the bullwhip effect in supply chains.", "ex_ar": "ضعف التواصل يسبب تذبذباً حاداً في الطلب عبر سلاسل الإمداد.", "category": "⚙️ سلاسل الإمداد والتخطيط"},
    {"en": "3PL (Third-Party Logistics)", "ar": "اللوجستيات الطرف الثالث", "pronunciation": "ثْرِي بِي إل", "ex_en": "We outsourced our warehousing to a reliable 3PL company.", "ex_ar": "قمنا بإسناد التخزين لدينا إلى شركة لوجستيات طرف ثالث موثوقة.", "category": "⚙️ سلاسل الإمداد والتخطيط"},

    # --- 4. التنفيذ وتوصيل الميل الأخير ---
    {"en": "Last Mile Delivery", "ar": "توصيل الميل الأخير", "pronunciation": "لَاسْت مَايْل دِيلِيفِري", "ex_en": "Last mile delivery is the most critical part of e-commerce.", "ex_ar": "توصيل الميل الأخير هو الجزء الأكثر أهمية في التجارة الإلكترونية.", "category": "📦 التنفيذ والميل الأخير"},
    {"en": "Fulfillment Center", "ar": "مركز تنفيذ الطلبات", "pronunciation": "فُولْفِيلْمِينْت سِينْتَر", "ex_en": "The fulfillment center processes thousands of orders daily.", "ex_ar": "يقوم مركز تنفيذ الطلبات بمعالجة آلاف الطلبات يومياً.", "category": "📦 التنفيذ والميل الأخير"},
    {"en": "Order Picking", "ar": "تجهيز / التقاط الطلبات", "pronunciation": "أُورْدَر بِيكِينْج", "ex_en": "Automated order picking is faster and reduces errors.", "ex_ar": "الالتقاط الآلي للطلبات أسرع ويقلل من الأخطاء البشريّة.", "category": "📦 التنفيذ والميل الأخير"},
    {"en": "Consignee", "ar": "المستلم / المرسل إليه", "pronunciation": "كَانْسَايْ نِي", "ex_en": "The consignee must sign the delivery receipt.", "ex_ar": "يجب على المستلم التوقيع على إيصال استلام الشحنة.", "category": "📦 التنفيذ والميل الأخير"},
    {"en": "Courier", "ar": "ساعي التوصيل / المندوب", "pronunciation": "كُورِيَر", "ex_en": "The courier will deliver the package to your doorstep.", "ex_ar": "يقوم المندوب بتسليم الطرد إلى عتبة بابك.", "category": "📦 التنفيذ والميل الأخير"},
    {"en": "Reverse Logistics", "ar": "اللوجستيات العكسية / إدارة المرتجعات", "pronunciation": "رِيفِيرْس لُوجِيسْتِيكْس", "ex_en": "Reverse logistics handles product returns and recycling.", "ex_ar": "تتعامل اللوجستيات العكسية مع مرتجعات المنتجات وإعادة تدويرها.", "category": "📦 التنفيذ والميل الأخير"},

    # --- 5. الجمارك والتجارة الدولية ---
    {"en": "Customs Clearance", "ar": "التخليص الجمركي", "pronunciation": "كَاسْتَمْز كْلِيرَانْس", "ex_en": "Customs clearance usually takes two business days.", "ex_ar": "التخليص الجمركي يستغرق عادةً يومي عمل.", "category": "📑 الجمارك والتجارة الدولية"},
    {"en": "Tariff", "ar": "التعريفة الجمركية", "pronunciation": "تَارِيف", "ex_en": "The government imposed a new tariff on imported electronics.", "ex_ar": "فرضت الحكومة تعريفة جمركية جديدة على الإلكترونيات المستوردة.", "category": "📑 الجمارك والتجارة الدولية"},
    {"en": "Incoterms", "ar": "مصطلحات التجارة الدولية", "pronunciation": "إِنْكُوتِيرْمز", "ex_en": "FOB and CIF are widely used Incoterms.", "ex_ar": "تعتبر مصطلحات FOB و CIF من أكثر مصطلحات التجارة الدولية استخداماً.", "category": "📑 الجمارك والتجارة الدولية"},
    {"en": "Bonded Warehouse", "ar": "المستودع الجمركي / البوندد", "pronunciation": "بُونْدِد وِيرْ هَاوْس", "ex_en": "Goods are stored in a bonded warehouse before duties are paid.", "ex_ar": "تُخزن البضائع في مستودع جمركي معلق الرسوم قبل دفع الضرائب.", "category": "📑 الجمارك والتجارة الدولية"},
    {"en": "Duty Free", "ar": "معفى من الرسوم الجمركية", "pronunciation": "دْيُوتِي فْرِي", "ex_en": "Some essential medical goods are duty-free.", "ex_ar": "بعض السلع الطبية الأساسية معفاة تماماً من الرسوم الجمركية.", "category": "📑 الجمارك والتجارة الدولية"},

    # --- 6. التقنيات والتحليلات اللوجستية ---
    {"en": "WMS (Warehouse Management System)", "ar": "نظام إدارة المستودعات", "pronunciation": "دَبْلِيُو إم إس", "ex_en": "The WMS tracks every item location inside the facility.", "ex_ar": "يتتبع نظام WMS موقع كل عنصر بدقة داخل المنشأة.", "category": "💻 التقنيات والتحليلات اللوجستية"},
    {"en": "TMS (Transportation Management System)", "ar": "نظام إدارة النقل", "pronunciation": "تي إم إس", "ex_en": "We use a TMS to optimize delivery routes.", "ex_ar": "نحن نستخدم نظام TMS لتحسين وتخطيط مسارات التوصيل.", "category": "💻 التقنيات والتحليلات اللوجستية"},
    {"en": "Tracking Number", "ar": "رقم التتبع", "pronunciation": "تْرَاكِينْج نَمْبَر", "ex_en": "Please provide the tracking number for live updates.", "ex_ar": "من فضلك زودنا برقم التتبع للحصول على تحديثات مباشرة.", "category": "💻 التقنيات والتحليلات اللوجستية"},
    {"en": "Cold Chain", "ar": "سلسلة التبريد", "pronunciation": "كُولْد تَشِين", "ex_en": "Vaccines require a strict cold chain during transit.", "ex_ar": "تتطلب اللقاحات سلسلة تبريد صارمة ومستمرة أثناء النقل.", "category": "💻 التقنيات والتحليلات اللوجستية"},
    {"en": "Lead Time Variability", "ar": "تقلب وتذبذب وقت التوريد", "pronunciation": "لِيد تَايْم فِيرِيَابِيلِيتِي", "ex_en": "Lead time variability can cause severe stockouts.", "ex_ar": "يمكن أن يتسبب تقلب وقت التوريد في نفاد خطير للمخزون.", "category": "💻 التقنيات والتحليلات اللوجستية"}
]
